config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "articles#index"
  
  resource :contacts, only: [:new, :create]
  resources :articles do
    resources :comments, only: [:create] 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  validates :title, length: { maximum: 140 }
  validates :text, length: { maximum: 4000 }

  has_many :comments
  belongs_to :user
  
  def subject
    title
  end
  
  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  validates :author, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 4000 }  
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  
validates :email, format:{ :with => /@/}
validates :name, presence: true
validates :email, presence: true
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :email, :password, :password_confirmation])
  devise_parameter_sanitizer.permit(:account_update, keys:[:username, :email, :password, :password_confirmation, :current_password])
end
end

app/controllers/articles_controller.rb
require 'pry'
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit]
  before_action :current_article, only: [:show, :edit, :update]
  
  def index
    @articles = Article.all
  end
  
  def show
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if current_user.id == @article.user_id
      @article.text = article_params[:text]
      @article.title = article_params[:title]
      @article.save
            
      redirect_to article_path
    else
      flash.alert = "This isn't your article you can't change it"
      redirect_to articles_path
    end
  end
  
  private
  
  def current_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :text, :user_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    comment = Comment.new(comment_params)
    comment.save
    redirect_to comment.article
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:author, :body, :article_id).to_h.merge(params.permit(:article_id).to_h)
  end
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  
  end
  
  def create
    message = Contact.new(contact_params)    
    if message.save
    else
      render 'new'
    end
    
  end
  
  private
  
  def contact_params
    params.permit(:email, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |f|%>
<%=f.hidden_field :user_id, value: current_user.id if signed_in?%>
<%=f.text_field :title%><br>
<%=f.text_area :text, size: "75x15" %><br>
<%=f.submit class: 'btn btn-secondary'%>
<%end%>

app/views/articles/edit.html.erb
<h1> Edit article</h1>
<%= render 'form'%>

app/views/articles/index.html.erb
<h1> <%= t('article.title')%></h1>
<%=link_to 'Add article', new_article_path, class: 'btn btn-primary'%>
<ol> 
<%@articles.reverse.each do |article|%>
<li>
<%= link_to "#{article.title}", article_path(article), style: 'color: #474a51' %>
</li>
<%end%>
</ol>

app/views/articles/new.html.erb
<h1> Create new article </h1>
<%= render 'form'%>

app/views/articles/show.html.erb
<h1> This is article </h2>
<p> <%=@article.title%></p>
<p> <%=@article.text%></p>
<%=link_to 'Edit article', edit_article_path, class: 'btn btn-success' %>
<%@article.comments.each do |comment|%>
<p> * <%=comment.author%> write : <%=comment.body%> </p>
<%end%>
<%if user_signed_in?%>
<%=form_with model: [@article, @article.comments.build], method: :post do |f|%>
  <%= f.text_field :author, value: current_user.name, type: :hidden%> <br>
  <%= f.text_area :body, size: "70x5", placeholder: 'Input your comment' %> <br>
  <%=f.submit%>  
<%end%>
<%end%>

app/views/contacts/create.html.erb
<h2> Thanks for your message! </h2>

app/views/contacts/new.html.erb
<h1> <%=t('contacts.contact_us')%>  </h1>
<%=form_with url: contacts_path do |f|%>
  <p> 
    <%=f.text_field :email, placeholder: 'Input your email'%>
  </p>
  <p>
    <%=f.text_area :message, size: '75x10', placeholder: 'Input your message'%>
  </p>
  <p>
    <%=f.submit 'Send message', class: 'btn btn-primary' %>
  </p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogEx4</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <%# connection boot-strap %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  
  <body>
  
      <div class= "container">
          <div class="row">
          <nav class="navbar navbar-dark bg-dark">
            <div class='col-1'></div>
            <div class="col-2">
              <%=link_to t('nav.title'), articles_path, class: "navbar-brand", style: 'font-size: 180%' %>
            </div>
            <div class='col-1'>
              <%=link_to t('nav.contact_us'), new_contacts_path, class: "navbar-nav", style: 'color: #BEBEBE' %>  
            </div>
            <div class='col-7'></div>
            <div class="col-1" >
              <%if user_signed_in?%>
              <%=link_to t('nav.logout', user_name: current_user.name), destroy_user_session_path, method: :delete,
                                                                          class: 'btn btn-success'%>
              <%else%>
              <%=link_to t('nav.login'), new_user_session_path, class: 'btn btn-danger'%>
              <%end%>
              </div>
          </nav>
          </div> <%#row closed%> 
        </div> <%#container closed%>
        
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        
        <div class='container'>
          <%= yield %>
          
        </div>
    
  </body>
</html>